version: "3.9"

services:
  db:
    image: postgres:16
    container_name: flyway_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: flyway_travels
      POSTGRES_USER: flyway_user
      POSTGRES_PASSWORD: flyway_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
